"""add category and ticket relationships

Revision ID: 650b210f5706
Revises: 
Create Date: 2026-09-15 11:53:31.616620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650b210f5706'
down_revision = '000000000001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tickets_created_by_id_users', 'users', ['created_by_id'], ['id'])
        batch_op.create_foreign_key('fk_tickets_category_id_categories', 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # Resolve actual names as old MySQL installations used generated FK names.
    foreign_keys = sa.inspect(op.get_bind()).get_foreign_keys("tickets")
    with op.batch_alter_table("tickets") as batch_op:
        for foreign_key in foreign_keys:
            if foreign_key["constrained_columns"] == ["created_by_id"]:
                batch_op.drop_constraint(foreign_key["name"], type_="foreignkey")
        batch_op.drop_column("created_by_id")
        for foreign_key in foreign_keys:
            if foreign_key["constrained_columns"] == ["category_id"]:
                batch_op.drop_constraint(foreign_key["name"], type_="foreignkey")
        batch_op.drop_column("category_id")
