"""add resolution confirmation

Revision ID: 7acee10cc88b
Revises: ade16b0913aa
Create Date: 2026-09-15 19:36:48.833333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7acee10cc88b'
down_revision = 'ade16b0913aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolution_confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('resolution_confirmed')

    # ### end Alembic commands ###
