"""add ticket assignee

Revision ID: ade16b0913aa
Revises: 650b210f5706
Create Date: 2026-09-15 13:27:24.196767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ade16b0913aa'
down_revision = '650b210f5706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tickets_assigned_to_id_users', 'users', ['assigned_to_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # Resolve actual names as old MySQL installations used generated FK names.
    foreign_keys = sa.inspect(op.get_bind()).get_foreign_keys("tickets")
    with op.batch_alter_table("tickets") as batch_op:
        for foreign_key in foreign_keys:
            if foreign_key["constrained_columns"] == ["assigned_to_id"]:
                batch_op.drop_constraint(foreign_key["name"], type_="foreignkey")
        batch_op.drop_column("assigned_to_id")
